entity_limit.entity_limit.*:
  type: config_entity
  label: 'Entity Limit config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    limit:
      type: integer
      label: 'Limit'
    entities:
      type: sequence
      label: 'Entities'
      sequence:
        type: entity_limit.entities.[%key]
    uuid:
      type: string

entity_limit.settings:
  type: config_object
  label: Entity Limit settings
  mapping:
    allowed_entities:
      type: sequence
      sequence:
        type: string

entity_limit.entities.*:
  type: config_object
  lable: Enable
  mapping:
    enable:
      type: integer
    bundles:
      type: sequence
      sequence:
        type: string
