entity.entity_limit.*:
  type: config_entity
  label: 'Entity Limit config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    plug-in_id:
      type: string
      label: 'Plug-in ID'
    entity_type:
      type: string
      label: 'Entity Type'
    entity_bundle:
      type: sequence
      label: 'Entity Bundles'
      sequence:
        type: entity_limit.bundle.[%key]
    limits:
      type: sequence
      sequence:
        type: entity_limit.limit.[%key]
    uuid:
      type: string

entity.entity_limit.bundle.*:
  type: config_object
  label: 'Entity Bundles'
  mapping:
    enable:
      type: integer
    bundles:
      type: sequence
      sequence:
        type: string

entity.limit.*:
  type: config_object
  lable: Enable
  mapping:
    id:
      type: integer
      label: 'User id or Role id'
    limit:
      type: integer
      label: 'Limit'