entity_limit.entity_limit.*:
  type: config_entity
  label: 'Entity Limit config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    plugin:
      type: string
      label: 'Select Plugin'
    entity_type:
      type: string
      label: 'Select Entity'
    entity_bundles:
      type: sequence
      label: 'Select Bundles'
      sequence:
        type: string
    limits:
      type: entity_limit.limits.[%parent.plugin]
    uuid:
      type: string

entity_limit.limits.*:
  type: sequence
  sequence:
    type: string

entity_limit.limits.user:
  type: mapping
  mapping:
    uid:
      type: string
      label: 'User Id'
    limit:
      type: string
      label: 'Limit'

entity_limit.limits.role:
  type: mapping
  mapping:
    rid:
      type: string
      label: 'Role Id'
    limit:
      type: string
      label: 'Limit'
